baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Moji-Moji - Failing journey of an aspiring pentester'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

# [[menus.main]]
# name = 'Tags'
# pageRef = '/tags'
# weight = 30

[[menus.main]]
name = 'Categorie'
pageRef = '/categories'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
