baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Moji-Moji - Failing journey of an aspiring pentester'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Tutti i post'
pageRef = '/posts'
weight = 20

# [[menus.main]]
# name = 'Tags'
# pageRef = '/tags'
# weight = 30

[[menus.main]]
name = 'Network'
pageRef = '/categories/network'
weight = 30

[[menus.main]]
name = 'Linux'
pageRef = '/categories/linux'
weight = 40

[[menus.main]]
name = 'Windows'
pageRef = '/categories/windows'
weight = 50

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
